[tox]
env_list = clean,py310,ruff,codespell,autofix

[testenv]
description = run unit tests
runner = uv-venv-lock-runner
setenv =
   PYTHONWARNINGS=default::DeprecationWarning
   OS_STDOUT_CAPTURE=1
   OS_STDERR_CAPTURE=1
   OS_TEST_TIMEOUT=60
commands = pytest {posargs}
depends =
    py310: clean

[testenv:clean]
skip_install = true
commands = coverage erase

[testenv:cover]
commands =
    pytest --cov {posargs}
    coverage combine
    coverage html -d cover
    coverage xml -o cover/coverage.xml
    coverage report

[testenv:autofix]
commands =
    ruff format {tox_root}
    codespell --skip "./cover/*," -w
    ruff check {tox_root} --fix

[testenv:black]
commands = black --check --diff {tox_root} {posargs}

[testenv:codespell]
commands = codespell --skip "./cover/*" {posargs}

[testenv:ruff]
description = Run Ruff checks
commands =
    ruff check {tox_root}
    ruff format {tox_root} --check

[testenv:mypy]
commands = mypy kube_custom_resource
